AWSTemplateFormatVersion: 2010-09-09
Description: Creates a R/W cross account user that authorizes access for CloudGuard
Metadata:
  Version: 2.0.0
Parameters:
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19
Resources:
  CrossAccountUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref CrossAccountUser
  CrossAccountUserCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CloudGuardCrossAccountUserCredentials
      SecretString: !Sub >-
        {"ACCESS_KEY":"${CrossAccountUserCredentials}","SECRET_KEY":"${CrossAccountUserCredentials.SecretAccessKey}"}
  CrossAccountUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub CloudGuard-Connect-RW-user${UniqueSuffix}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  CrossAccountReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RO-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardReadOnly
            Action:
              - ram:GetResourceShares
              - appflow:ListConnectors
              - account:GetAlternateContact
              - apigateway:GET
              - athena:GetQueryExecution
              - athena:GetWorkGroup
              - backup:ListBackupVaults
              - backup:ListTags
              - cognito-identity:DescribeIdentityPool
              - codeartifact:ListDomains
              - codeartifact:DescribeDomain
              - codeartifact:GetDomainPermissionsPolicy
              - codeartifact:ListTagsForResource
              - codeartifact:DescribeRepository
              - codebuild:GetResourcePolicy
              - cognito-idp:DescribeUserPool
              - cognito-idp:DescribeRiskConfiguration
              - macie2:DescribeBuckets
              - macie2:GetMacieSession
              - macie2:GetFindingStatistics
              - dynamodb:ListTagsOfResource
              - ec2:SearchTransitGatewayRoutes
              - elasticfilesystem:Describe*
              - elasticache:ListTagsForResource
              - es:ListTags
              - eks:DescribeNodegroup
              - eks:ListNodegroups
              - glacier:ListTagsForVault
              - glue:GetConnections
              - glue:GetSecurityConfigurations
              - glue:GetMLTransforms
              - glue:GetCrawlers
              - glue:GetDevEndpoints
              - glue:GetJobs
              - glue:GetDataCatalogEncryptionSettings
              - healthlake:ListFHIRDatastores
              - healthlake:ListTagsForResource
              - inspector2:ListFindings
              - inspector2:BatchGetAccountStatus
              - inspector2:ListFindingAggregations
              - inspector2:ListCoverage
              - kafka:ListClusters
              - kinesis:List*
              - kinesis:Describe*
              - kinesisvideo:Describe*
              - kinesisvideo:List*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:ListLogDeliveries
              - memorydb:DescribeACLs
              - memorydb:DescribeParameters
              - memorydb:DescribeSnapshots
              - memorydb:DescribeUsers
              - memorydb:ListTags
              - mq:DescribeBroker
              - mq:ListBrokers
              - network-firewall:DescribeFirewall
              - network-firewall:DescribeLoggingConfiguration
              - network-firewall:ListFirewalls
              - network-firewall:DescribeRuleGroup
              - network-firewall:DescribeFirewallPolicy
              - personalize:DescribeDatasetGroup
              - personalize:ListDatasetGroups
              - personalize:ListTagsForResource
              - s3:List*
              - secretsmanager:DescribeSecret
              - ses:ListEmailIdentities
              - ses:GetEmailIdentity
              - ses:ListConfigurationSets
              - ses:GetConfigurationSet
              - sns:ListSubscriptions
              - sns:ListTagsForResource
              - sns:GetPlatformApplicationAttributes
              - sns:ListPlatformApplications
              - states:DescribeStateMachine
              - transcribe:Get*
              - transcribe:List*
              - translate:GetTerminology
              - waf-regional:ListResourcesForWebACL
              - wafv2:ListWebACLs
              - wafv2:ListResourcesForWebACL
              - eks:ListFargateProfiles
              - eks:DescribeFargateProfile
              - ecr:GetRegistryScanningConfiguration
              - ecr:DescribeRegistry
              - aps:ListWorkspaces
              - aps:DescribeWorkspace
              - aps:DescribeLoggingConfiguration
              - cloudformation:ListTypes
              - cloudformation:DescribeType
              - cloudformation:BatchDescribeTypeConfigurations
              - amplify:ListApps
              - serverlessrepo:GetApplication
              - simspaceweaver:ListSimulations
              - simspaceweaver:ListTagsForResource
              - simspaceweaver:DescribeSimulation
              - grafana:DescribeWorkspace
              - mediaconvert:ListJobs
              - mediaconvert:ListPresets
              - mediaconvert:ListQueues
              - mediaconvert:ListTagsForResource
              - mediapackage:ListChannels
              - mediastore:ListTagsForResource
              - mediapackage:ListHarvestJobs
              - dataexchange:ListTagsForResource
              - dataexchange:ListEventActions
              - dataexchange:ListJobs
              - drs:DescribeJobs
              - drs:DescribeJobLogItems
              - drs:DescribeSourceServers
              - drs:DescribeRecoverySnapshots
              - drs:DescribeSourceNetworks
              - drs:DescribeRecoveryInstances
              - drs:GetFailbackReplicationConfiguration
              - drs:DescribeReplicationConfigurationTemplates
              - drs:DescribeLaunchConfigurationTemplates
              - timestream:ListBatchLoadTasks
              - timestream:ListDatabases
              - timestream:ListTables
              - timestream:ListTagsForResource
            Effect: Allow
            Resource: '*'
          - Sid: ElasticbeanstalkConfigurationSettingsPermission
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::elasticbeanstalk-env-resources-??*?/*
      Users:
        - !Ref CrossAccountUser
  CrossAccountReadWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RW-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardWrite
            Action:
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:ModifyNetworkInterfaceAttribute
              - ec2:CreateTags
              - ec2:DeleteTags
            Effect: Allow
            Resource: '*'
      Users:
        - !Ref CrossAccountUser
