AWSTemplateFormatVersion: 2010-09-09
Description: Creates a read-only cross account user that authorizes access for CloudGuard
Metadata:
  Version: 2.0.0
Parameters:
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19
Resources:
  CrossAccountUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref CrossAccountUser
  CrossAccountUserCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CloudGuardCrossAccountUserCredentials
      SecretString: !Sub >-
        {"ACCESS_KEY":"${CrossAccountUserCredentials}","SECRET_KEY":"${CrossAccountUserCredentials.SecretAccessKey}"}
  CrossAccountUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub CloudGuard-Connect-RO-user${UniqueSuffix}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  CrossAccountReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RO-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardReadOnly
            Action:
              - account:GetAlternateContact
              - apigateway:GET
              - athena:GetQueryExecution
              - athena:GetWorkGroup
              - backup:ListBackupVaults
              - backup:ListTags
              - cognito-identity:DescribeIdentityPool
              - cognito-idp:DescribeUserPool
              - cognito-idp:DescribeRiskConfiguration
              - macie2:DescribeBuckets
              - macie2:GetMacieSession
              - macie2:GetFindingStatistics
              - dynamodb:ListTagsOfResource
              - ec2:SearchTransitGatewayRoutes
              - elasticfilesystem:Describe*
              - elasticache:ListTagsForResource
              - es:ListTags
              - eks:DescribeNodegroup
              - eks:ListNodegroups
              - glue:GetConnections
              - glue:GetSecurityConfigurations
              - inspector2:ListFindings
              - inspector2:BatchGetAccountStatus
              - inspector2:ListFindingAggregations
              - inspector2:ListCoverage
              - kafka:ListClusters
              - kinesis:List*
              - kinesis:Describe*
              - kinesisvideo:Describe*
              - kinesisvideo:List*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:ListLogDeliveries
              - mq:DescribeBroker
              - mq:ListBrokers
              - network-firewall:DescribeFirewall
              - network-firewall:DescribeLoggingConfiguration
              - network-firewall:ListFirewalls
              - network-firewall:DescribeRuleGroup
              - network-firewall:DescribeFirewallPolicy
              - personalize:DescribeDatasetGroup
              - personalize:ListDatasetGroups
              - s3:List*
              - secretsmanager:DescribeSecret
              - sns:ListSubscriptions
              - sns:ListTagsForResource
              - sns:GetPlatformApplicationAttributes
              - sns:ListPlatformApplications
              - states:DescribeStateMachine
              - transcribe:Get*
              - transcribe:List*
              - translate:GetTerminology
              - waf-regional:ListResourcesForWebACL
              - wafv2:ListWebACLs
              - wafv2:ListResourcesForWebACL
              - eks:ListFargateProfiles
              - eks:DescribeFargateProfile
            Effect: Allow
            Resource: '*'
          - Sid: ElasticbeanstalkConfigurationSettingsPermission
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::elasticbeanstalk-env-resources-??*?/*
      Users:
        - !Ref CrossAccountUser
