AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a R/W cross account user that authorizes access for CloudGuard'
Metadata:
  Version: 2.0.0 

Resources:
  CrossAccountUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties: 
      Status: Active
      UserName: !Ref CrossAccountUser
          
  CrossAccountUserCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CloudGuardCrossAccountUserCredentials
      SecretString: !Sub '{"ACCESS_KEY":"${CrossAccountUserCredentials}","SECRET_KEY":"${CrossAccountUserCredentials.SecretAccessKey}"}'
            
  CrossAccountUser:
    Type: AWS::IAM::User
    Properties:
      # max 64 chars
      UserName: 'CloudGuard-Connect-RW-user'
     
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

      Policies:
        - PolicyName: CloudGuard-Connect-RO-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudGuardReadOnly
                Action:
                  - 'aws-marketplace:*'
                  - 'apigateway:GET'
                  - 'athena:GetQueryExecution'
                  - 'athena:GetWorkGroup'
                  - 'backup:ListBackupVaults'
                  - 'cognito-identity:DescribeIdentityPool'
                  - 'cognito-idp:DescribeUserPool'
                  - 'cognito-idp:DescribeRiskConfiguration'
                  - 'dynamodb:ListTagsOfResource'
                  - 'ec2:SearchTransitGatewayRoutes'
                  - 'elasticfilesystem:Describe*'
                  - 'elasticache:ListTagsForResource'
                  - 'es:ListTags'                  
                  - 'eks:ListNodegroups'
                  - 'eks:DescribeNodegroup'
                  - 'glue:GetConnections'
                  - 'glue:GetSecurityConfigurations'
                  - 'kafka:ListClusters'
                  - 'kinesis:List*'
                  - 'kinesis:Describe*'
                  - 'kinesisvideo:Describe*'
                  - 'kinesisvideo:List*'
                  - 'logs:Get*'
                  - 'logs:FilterLogEvents'
                  - 'logs:ListLogDeliveries'
                  - 'mq:DescribeBroker'
                  - 'mq:ListBrokers'
                  - 'network-firewall:DescribeFirewall'
                  - 'network-firewall:DescribeLoggingConfiguration'
                  - 'network-firewall:ListFirewalls'
                  - 'network-firewall:DescribeRuleGroup'
                  - 'network-firewall:DescribeFirewallPolicy'
                  - 'personalize:DescribeDatasetGroup'
                  - 'personalize:ListDatasetGroups'
                  - 's3:List*'
                  - 'secretsmanager:DescribeSecret'
                  - 'sns:ListSubscriptions'
                  - 'sns:ListTagsForResource'
                  - 'sns:GetPlatformApplicationAttributes'
                  - 'sns:ListPlatformApplications'
                  - 'states:DescribeStateMachine'
                  - 'transcribe:Get*'
                  - 'transcribe:List*'
                  - 'translate:GetTerminology'
                  - 'waf-regional:ListResourcesForWebACL'
                  - 'wafv2:ListWebACLs'
                  - 'wafv2:ListResourcesForWebACL'
                  - 'eks:ListFargateProfiles'
                  - 'eks:DescribeFargateProfile'
                Effect: Allow
                Resource: '*'
              - Sid: ElasticbeanstalkConfigurationSettingsPermission
                Action:
                  - 's3:GetObject'
                Effect: Allow
                Resource: !Sub 'arn:${AWS::Partition}:s3:::elasticbeanstalk-env-resources-??*?/*' 
        - PolicyName: CloudGuard-Connect-RW-policy         
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudGuardWrite
                Action:
                  - 'ec2:AuthorizeSecurityGroupEgress'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:RevokeSecurityGroupEgress'
                  - 'ec2:RevokeSecurityGroupIngress'
                  - 'ec2:ModifyNetworkInterfaceAttribute'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                Effect: Allow
                Resource: '*'             

 