AWSTemplateFormatVersion: 2010-09-09
Description: Create a R/W cross account role that authorizes access for CloudGuard Dome9.
Metadata:
  Version: 2.0.0
Parameters:
  CloudGuardAwsAccountId:
    Description: CloudGuard instance AWS AccountId that is requiring external trust
    Type: String
  RoleExternalTrustSecret:
    Description: CloudGuard generated unique id for assuming external trust
    Type: String
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19
Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudGuard-Connect-RW-role${UniqueSuffix}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${CloudGuardAwsAccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref RoleExternalTrustSecret
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  CrossAccountReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RO-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardReadOnly
            Action:
              - fms:ListTagsForResource
              - fms:GetAdminScope
              - fms:GetPolicy
              - fms:ListAdminAccountsForOrganization
              - forecast:DescribeDataset
              - forecast:DescribeAutoPredictor
              - forecast:DescribePredictor
              - forecast:ListDatasetGroups
              - forecast:ListExplainabilities
              - forecast:ListForecasts
              - forecast:ListMonitors
              - forecast:ListPredictors
              - forecast:ListTagsForResource
              - comprehend:ListEndpoints
              - comprehend:ListFlywheels
              - appfabric:ListAppBundles
              - appfabric:GetAppBundle
              - appfabric:ListTagsForResource
              - lightsail:GetRelationalDatabases
              - lightsail:GetRelationalDatabaseParameters
              - lightsail:GetLoadBalancerTlsCertificates
              - lightsail:GetDomains
              - lightsail:GetDistributions
              - batch:DescribeJobQueues
              - kinesisanalytics:ListTagsForResource
              - ram:GetResourceShares
              - appflow:ListConnectors
              - airflow:GetEnvironment
              - account:GetAlternateContact
              - apigateway:GET
              - athena:GetQueryExecution
              - athena:GetWorkGroup
              - backup:ListBackupVaults
              - backup:ListTags
              - cassandra:Select
              - cognito-identity:DescribeIdentityPool
              - codeartifact:ListDomains
              - codeartifact:DescribeDomain
              - codeartifact:GetDomainPermissionsPolicy
              - codeartifact:ListTagsForResource
              - codeartifact:DescribeRepository
              - codebuild:GetResourcePolicy
              - cognito-idp:DescribeUserPool
              - cognito-idp:DescribeRiskConfiguration
              - compute-optimizer:GetRecommendationSummaries
              - macie2:DescribeBuckets
              - macie2:GetMacieSession
              - macie2:GetFindingStatistics
              - verifiedpermissions:ListPolicyStores
              - verifiedpermissions:GetPolicyStore
              - dynamodb:ListTagsOfResource
              - ec2:SearchTransitGatewayRoutes
              - elasticfilesystem:Describe*
              - elasticache:ListTagsForResource
              - es:ListTags
              - cloudhsm:DescribeClusters
              - cloudhsm:DescribeBackups
              - eks:DescribeNodegroup
              - eks:ListNodegroups
              - glacier:ListTagsForVault
              - glue:GetConnections
              - glue:GetSecurityConfigurations
              - glue:GetMLTransforms
              - glue:GetCrawlers
              - glue:GetDevEndpoints
              - glue:GetJobs
              - glue:GetDataCatalogEncryptionSettings
              - healthlake:ListFHIRDatastores
              - healthlake:ListTagsForResource
              - inspector2:ListFindings
              - inspector2:BatchGetAccountStatus
              - inspector2:ListFindingAggregations
              - inspector2:ListCoverage
              - kafka:ListClusters
              - kendra:ListTagsForResource
              - devops-guru:DescribeServiceIntegration
              - kinesis:List*
              - kinesis:Describe*
              - kinesisvideo:Describe*
              - kinesisvideo:List*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:ListLogDeliveries
              - codebuild:ListBuilds
              - codebuild:BatchGetBuilds
              - codepipeline:ListWebhooks
              - memorydb:DescribeACLs
              - memorydb:DescribeParameters
              - memorydb:DescribeSnapshots
              - memorydb:DescribeUsers
              - memorydb:ListTags
              - mq:DescribeBroker
              - mq:ListBrokers
              - network-firewall:DescribeFirewall
              - network-firewall:DescribeLoggingConfiguration
              - network-firewall:ListFirewalls
              - network-firewall:DescribeRuleGroup
              - network-firewall:DescribeFirewallPolicy
              - personalize:DescribeDatasetGroup
              - personalize:ListDatasetGroups
              - personalize:ListTagsForResource
              - s3:List*
              - secretsmanager:DescribeSecret
              - ses:ListEmailIdentities
              - ses:GetEmailIdentity
              - ses:ListConfigurationSets
              - ses:GetConfigurationSet
              - sns:ListSubscriptions
              - sns:ListTagsForResource
              - sns:GetPlatformApplicationAttributes
              - sns:ListPlatformApplications
              - states:DescribeStateMachine
              - transcribe:Get*
              - transcribe:List*
              - translate:GetTerminology
              - waf-regional:ListResourcesForWebACL
              - wafv2:ListWebACLs
              - wafv2:ListResourcesForWebACL
              - eks:ListFargateProfiles
              - eks:DescribeFargateProfile
              - ecr:GetRegistryScanningConfiguration
              - ecr:DescribeRegistry
              - appstream:DescribeUsageReportSubscriptions
              - aps:ListWorkspaces
              - aps:DescribeWorkspace
              - aps:DescribeLoggingConfiguration
              - cloudformation:ListTypes
              - cloudformation:DescribeType
              - cloudformation:BatchDescribeTypeConfigurations
              - amplify:ListApps
              - serverlessrepo:GetApplication
              - simspaceweaver:ListSimulations
              - simspaceweaver:ListTagsForResource
              - simspaceweaver:DescribeSimulation
              - grafana:DescribeWorkspace
              - mediaconvert:ListJobs
              - mediaconvert:ListPresets
              - mediaconvert:ListQueues
              - mediaconvert:ListTagsForResource
              - mediapackage:ListChannels
              - mediastore:ListTagsForResource
              - mediatailor:ListChannels
              - mediatailor:GetChannelPolicy
              - mediatailor:ListPlaybackConfigurations
              - mediatailor:ListSourceLocations
              - mediapackage:ListHarvestJobs
              - dataexchange:ListTagsForResource
              - dataexchange:ListEventActions
              - dataexchange:ListJobs
              - elastictranscoder:ListPresets
              - medialive:ListInputs
              - medialive:ListMultiplexes
              - medialive:ListReservations
              - medialive:ListInputSecurityGroups
              - drs:DescribeJobs
              - drs:DescribeJobLogItems
              - drs:DescribeSourceServers
              - drs:DescribeRecoverySnapshots
              - drs:DescribeSourceNetworks
              - drs:DescribeRecoveryInstances
              - drs:GetFailbackReplicationConfiguration
              - drs:DescribeReplicationConfigurationTemplates
              - drs:DescribeLaunchConfigurationTemplates
              - timestream:ListBatchLoadTasks
              - timestream:ListDatabases
              - timestream:ListTables
              - timestream:ListTagsForResource
              - timestream:DescribeEndpoints
              - signer:ListTagsForResource
              - signer:ListSigningJobs
              - signer:ListSigningPlatforms
              - signer:ListSigningProfiles
              - storagegateway:DescribeSMBFileShares
              - nimble:ListStudios
              - ds:ListTagsForResource
              - support:DescribeCases
              - support:DescribeSeverityLevels
              - outposts:ListOutposts
              - waf-regional:ListLoggingConfigurations
              - wafv2:GetIPSet
              - finspace:ListTagsForResource
              - lakeformation:GetDataLakeSettings
            Effect: Allow
            Resource: '*'
          - Sid: ElasticbeanstalkConfigurationSettingsPermission
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::elasticbeanstalk-env-resources-??*?/*
      Roles:
        - !Ref CrossAccountRole
  CrossAccountReadWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RW-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardWrite
            Action:
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:ModifyNetworkInterfaceAttribute
              - ec2:CreateTags
              - ec2:DeleteTags
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref CrossAccountRole
Outputs:
  CrossAccountRoleArn:
    Description: The CrossAccount Role Arn
    Value: !GetAtt CrossAccountRole.Arn
