AWSTemplateFormatVersion: 2010-09-09
Description: Create a R/W cross account role that authorizes access for CloudGuard Dome9.
Metadata:
  Version: 2.0.0
Parameters:
  CloudGuardAwsAccountId:
    Description: CloudGuard instance AWS AccountId that is requiring external trust
    Type: String
  RoleExternalTrustSecret:
    Description: CloudGuard generated unique id for assuming external trust
    Type: String
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19
Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CloudGuard-Connect-RW-role${UniqueSuffix}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${CloudGuardAwsAccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref RoleExternalTrustSecret
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
  CrossAccountReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RO-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardReadOnly
            Action:
              - account:GetAlternateContact
              - apigateway:GET
              - athena:GetQueryExecution
              - athena:GetWorkGroup
              - backup:ListBackupVaults
              - backup:ListTags
              - cognito-identity:DescribeIdentityPool
              - cognito-idp:DescribeUserPool
              - cognito-idp:DescribeRiskConfiguration
              - macie2:DescribeBuckets
              - macie2:GetMacieSession
              - macie2:GetFindingStatistics
              - dynamodb:ListTagsOfResource
              - ec2:SearchTransitGatewayRoutes
              - elasticfilesystem:Describe*
              - elasticache:ListTagsForResource
              - es:ListTags
              - eks:DescribeNodegroup
              - eks:ListNodegroups
              - glue:GetConnections
              - glue:GetSecurityConfigurations
              - glue:GetMLTransforms
              - glue:GetCrawlers
              - glue:GetDevEndpoints
              - glue:GetJobs
              - glue:GetDataCatalogEncryptionSettings
              - inspector2:ListFindings
              - inspector2:BatchGetAccountStatus
              - inspector2:ListFindingAggregations
              - inspector2:ListCoverage
              - kafka:ListClusters
              - kinesis:List*
              - kinesis:Describe*
              - kinesisvideo:Describe*
              - kinesisvideo:List*
              - logs:Get*
              - logs:FilterLogEvents
              - logs:ListLogDeliveries
              - mq:DescribeBroker
              - mq:ListBrokers
              - network-firewall:DescribeFirewall
              - network-firewall:DescribeLoggingConfiguration
              - network-firewall:ListFirewalls
              - network-firewall:DescribeRuleGroup
              - network-firewall:DescribeFirewallPolicy
              - personalize:DescribeDatasetGroup
              - personalize:ListDatasetGroups
              - personalize:ListTagsForResource
              - s3:List*
              - secretsmanager:DescribeSecret
              - sns:ListSubscriptions
              - sns:ListTagsForResource
              - sns:GetPlatformApplicationAttributes
              - sns:ListPlatformApplications
              - states:DescribeStateMachine
              - transcribe:Get*
              - transcribe:List*
              - translate:GetTerminology
              - waf-regional:ListResourcesForWebACL
              - wafv2:ListWebACLs
              - wafv2:ListResourcesForWebACL
              - eks:ListFargateProfiles
              - eks:DescribeFargateProfile
              - ecr:GetRegistryScanningConfiguration
              - ecr:DescribeRegistry
            Effect: Allow
            Resource: '*'
          - Sid: ElasticbeanstalkConfigurationSettingsPermission
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:${AWS::Partition}:s3:::elasticbeanstalk-env-resources-??*?/*
      Roles:
        - !Ref CrossAccountRole
  CrossAccountReadWritePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub CloudGuard-Connect-RW-policy${UniqueSuffix}
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudGuardWrite
            Action:
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CreateSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:ModifyNetworkInterfaceAttribute
              - ec2:CreateTags
              - ec2:DeleteTags
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref CrossAccountRole
Outputs:
  CrossAccountRoleArn:
    Description: The CrossAccount Role Arn
    Value: !GetAtt CrossAccountRole.Arn
