AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create Dome9 Intelligence Policy that enable CloudGuard Dome9 to access CloudTrail data.'
Metadata:
  Version: 2.0.0

Parameters: 
  CloudtrailS3BucketName:    
    Description: Name of s3 bucket connected to cloudtrail
    Type: String
  CloudGuardRoleName:
    Description: Name of Cloud Guard Role to attached logic policy
    Type: String
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19

Resources:
  IntelligencePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'CloudGuard-for-intelligence${UniqueSuffix}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: Dome9S3ForLogic
            Action:
              - 's3:GetObject'
              - 's3:PutBucketNotification'                
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${CloudtrailS3BucketName}"
              - !Sub "arn:aws:s3:::${CloudtrailS3BucketName}/*"                     
      Roles:
        - !Ref CloudGuardRoleName
