AWSTemplateFormatVersion: '2010-09-09'
Description: 'Check Point CloudGuard Dome9 unified onboarding'
REPLACEMENT_METADATA:

Parameters:
  REPLACEMENT_PARAMETERS:
  RemoteStackModifyRoleExternalTrustSecret:
    Description: CloudGuard generated unique id for assuming external trust
    Type: String
  CloudGuardAwsAccountNumber:
    Description: The CloudGuard AWS account number
    Type: String
  ServerlessStage:
    Description: The Serverless stage name
    Type: String

REPLACEMENT_CONDITIONS:

Resources:

  CloudGuardOnboardingStackModifyRole:
    Type: AWS::IAM::Role
    Condition: RemoteStackModifyEnabled
    Properties:
      RoleName: !Sub 'CloudGuard-Onboarding-StackModify-role${UniqueSuffix}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
                AWS: !Sub 'arn:aws:iam::${CloudGuardAwsAccountNumber}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref RemoteStackModifyRoleExternalTrustSecret
  
      Policies:
        - PolicyName: !Sub 'CloudGuard-Lambda-StackModify-policy${UniqueSuffix}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - REPLACEMENT_SATCK_MODIFY_POLICY_STATEMENT
              - Sid: DeleteRolePolicy
                Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:DeleteRolePolicy
                  - iam:DeleteRole
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/CloudGuard-Onboarding-StackModify-role${UniqueSuffix}'

  StackModifyRoleWaiter: 
    Condition: RemoteStackModifyEnabled
    DependsOn: CloudGuardOnboardingStackModifyRole
    Type: "AWS::CloudFormation::WaitConditionHandle"

  Waiter: 
    Type: "AWS::CloudFormation::WaitConditionHandle"

  StackModifyIfEnabledWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties: 
      Handle: !If [RemoteStackModifyEnabled, !Ref StackModifyRoleWaiter, !Ref Waiter]
      Timeout: '1'
      Count: 0

  REPLACEMENT_SNS:

  REPLACEMENT_ORCHESTRATOR_ROLE:

  REPLACEMENT_ORCHESTRATOR:

  REPLACEMENT_ORCHESTRATOR_HELPER:

  CloudGuardOnboardingOrchestratorInvoke:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - CloudGuardOnboardingSnsPolicy
      - OrchestratorInvokePermission
      - OrchestratorSubscription
      - OrchestratorHelperInvokePermission
      - OrchestratorHelperSubscription
    Properties:
      REPLACEMENT_ORCHESTRATOR_INVOKE_PROPERTIES:
      OnboardingStackModifyRoleArn: !If [RemoteStackModifyEnabled, !GetAtt CloudGuardOnboardingStackModifyRole.Arn, '']
  