AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a read-only cross account role that authorizes access for CloudGuard Dome9.'
Metadata:
  Version: 2.0.0
  
Parameters: 
  CloudGuardAwsAccountId:    
    Description: CloudGuard instance AWS AccountId that is requiring external trust
    Type: String
  RoleExternalTrustSecret:    
    Description: CloudGuard generated unique id for assuming external trust
    Type: String
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CloudGuard-Connect-RO-role${UniqueSuffix}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
                AWS: !Sub 'arn:aws:iam::${CloudGuardAwsAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref RoleExternalTrustSecret
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

      Policies:
        - PolicyName: !Sub 'CloudGuard-Connect-RO-policy${UniqueSuffix}'
          PolicyDocument: REPLACEMENT_READONLY_POLICY

Outputs:
  CrossAccountRoleArn:
    Description: The CrossAccount Role Arn
    Value: !GetAtt CrossAccountRole.Arn