AWSTemplateFormatVersion: '2010-09-09'
Description: 'Check Point CloudGuard Dome9 unified onboarding'
REPLACEMENT_METADATA:

Parameters:
  REPLACEMENT_PARAMETERS:

REPLACEMENT_CONDITIONS:

Resources:
  CloudGuardOnboardingStackModifyCrossAccountUser:
    Type: AWS::IAM::User
    Condition: RemoteStackModifyEnabled
    Properties:
      UserName: !Sub 'CloudGuard-Onboarding-StackModify-user${UniqueSuffix}'

      Policies:
        - PolicyName: !Sub 'CloudGuard-Lambda-StackModify-policy${UniqueSuffix}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - REPLACEMENT_SATCK_MODIFY_POLICY_STATEMENT
              - Sid: DeleteUserPolicy
                Effect: Allow
                Action:
                  - iam:GetUser
                  - iam:DeleteUserPolicy
                  - iam:DeleteUser
                  - iam:DeleteAccessKey
                  - iam:ListAccessKeys
                  - iam:PutUserPolicy
                Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/CloudGuard-Onboarding-StackModify-user${UniqueSuffix}'

              - Sid: DeleteSecret
                Effect: Allow
                Action:
                  - secretsmanager:DeleteSecret 
                Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:*:*:secret:CloudGuardStackModifyCrossAccountUserCredentials*'

  StackModifyCrossAccountUserCredentials:
    Type: AWS::IAM::AccessKey
    Condition: RemoteStackModifyEnabled
    Properties: 
      Status: Active
      UserName: !Ref CloudGuardOnboardingStackModifyCrossAccountUser

  CloudGuardOnboardingStackModifyPermissions:
    Type: AWS::SecretsManager::Secret
    Condition: RemoteStackModifyEnabled
    Properties:
      Name: CloudGuardStackModifyCrossAccountUserCredentials
      SecretString: !Sub '{"ACCESS_KEY":"${StackModifyCrossAccountUserCredentials}","SECRET_KEY":"${StackModifyCrossAccountUserCredentials.SecretAccessKey}"}'

  REPLACEMENT_SNS:

  REPLACEMENT_ORCHESTRATOR_ROLE:
        
  REPLACEMENT_ORCHESTRATOR:

  REPLACEMENT_ORCHESTRATOR_HELPER:
      
  CloudGuardOnboardingOrchestratorInvoke:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - CloudGuardOnboardingSnsPolicy
      - OrchestratorInvokePermission
      - OrchestratorSubscription
      - OrchestratorHelperInvokePermission
      - OrchestratorHelperSubscription
    Properties:
      REPLACEMENT_ORCHESTRATOR_INVOKE_PROPERTIES: