AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a read-only cross account user that authorizes access for CloudGuard'
Metadata:
  Version: 2.0.0

Parameters:
  UniqueSuffix:
    Description: An optional suffix for all resources
    Type: String
    Default: ''
    MaxLength: 19

Resources:
  CrossAccountUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties: 
      Status: Active
      UserName: !Ref CrossAccountUser
          
  CrossAccountUserCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: CloudGuardCrossAccountUserCredentials
      SecretString: !Sub '{"ACCESS_KEY":"${CrossAccountUserCredentials}","SECRET_KEY":"${CrossAccountUserCredentials.SecretAccessKey}"}'
            
  CrossAccountUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'CloudGuard-Connect-RO-user${UniqueSuffix}'
     
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

      Policies:
        - PolicyName: !Sub 'CloudGuard-Connect-RO-policy${UniqueSuffix}'
          PolicyDocument: REPLACEMENT_READONLY_POLICY