AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a R/W cross account role that authorizes access for CloudGuard Dome9.'
Metadata:
  Version: 0.0.1
  
Parameters:
  CloudGuardAwsAccountId:    
    Description: CloudGuard instance AWS AccountId that is requiring external trust
    Type: String
  RoleExternalTrustSecret:   
    Description: CloudGuard generated unique id for assuming external trust
    Type: String

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role    
    Properties:
      # max 64 chars
      RoleName: 'CloudGuard-Connect-RW-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              # https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
                AWS: !Sub 'arn:aws:iam::${CloudGuardAwsAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub ${RoleExternalTrustSecret}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

      Policies:
        - PolicyName: CloudGuard-Connect-RO-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudGuardReadOnly
                Action:
                  - 'apigateway:GET'
                  - 'athena:GetQueryExecution'
                  - 'athena:GetWorkGroup'
                  - 'backup:ListBackupVaults'
                  - 'cognito-identity:DescribeIdentityPool'
                  - 'cognito-idp:DescribeUserPool'
                  - 'cognito-idp:DescribeRiskConfiguration'
                  - 'dynamodb:ListTagsOfResource'
                  - 'ec2:SearchTransitGatewayRoutes'
                  - 'elasticfilesystem:Describe*'
                  - 'elasticache:ListTagsForResource'
                  - 'es:ListTags'
                  - 'eks:DescribeNodegroup'
                  - 'eks:ListNodegroups'
                  - 'glue:GetConnections'
                  - 'glue:GetSecurityConfigurations'
                  - 'kafka:ListClusters'
                  - 'kinesis:List*'
                  - 'kinesis:Describe*'
                  - 'kinesisvideo:Describe*'
                  - 'kinesisvideo:List*'
                  - 'logs:Get*'
                  - 'logs:FilterLogEvents'
                  - 'logs:ListLogDeliveries'
                  - 'mq:DescribeBroker'
                  - 'mq:ListBrokers'
                  - 'network-firewall:DescribeFirewall'
                  - 'network-firewall:DescribeLoggingConfiguration'
                  - 'network-firewall:ListFirewalls'
                  - 'network-firewall:DescribeRuleGroup'
                  - 'network-firewall:DescribeFirewallPolicy'
                  - 'personalize:DescribeDatasetGroup'
                  - 'personalize:ListDatasetGroups'
                  - 's3:List*'
                  - 'secretsmanager:DescribeSecret'
                  - 'sns:ListSubscriptions'
                  - 'sns:ListTagsForResource'
                  - 'sns:GetPlatformApplicationAttributes'
                  - 'sns:ListPlatformApplications'
                  - 'states:DescribeStateMachine'
                  - 'transcribe:Get*'
                  - 'transcribe:List*'
                  - 'translate:GetTerminology'
                  - 'waf-regional:ListResourcesForWebACL'
                  - 'wafv2:ListWebACLs'
                  - 'wafv2:ListResourcesForWebACL'
                  - 'eks:ListFargateProfiles'
                  - 'eks:DescribeFargateProfile'
                Effect: Allow
                Resource: '*'
              - Sid: ElasticbeanstalkConfigurationSettingsPermission
                Action:
                  - 's3:GetObject'
                Effect: Allow
                Resource: 'arn:aws:s3:::elasticbeanstalk-env-resources-??*?/*'
        - PolicyName: CloudGuard-Connect-RW-policy         
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudGuardWrite
                Action:
                  - 'ec2:AuthorizeSecurityGroupEgress'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:RevokeSecurityGroupEgress'
                  - 'ec2:RevokeSecurityGroupIngress'
                  - 'ec2:ModifyNetworkInterfaceAttribute'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                Effect: Allow
                Resource: '*'             

 