CloudGuardOrchestratorRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: !Sub 'CloudGuard-Onboarding-Orchestrator-role${UniqueSuffix}'
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - 'sts:AssumeRole'
    Policies:
      - PolicyName: !Sub 'CloudGuard-Onboarding-Orchestrator-policy${UniqueSuffix}'
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CloudGuardOnboardingOrchestratorCloudformation
              Action:
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
              Effect: Allow
              Resource:
                - !Sub 'arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stack/CloudGuard-Onboarding*'
            - Sid: CloudGuardOnboardingOrchestratorCloudformationList
              Action:
                - 'cloudformation:ListStacks'
              Effect: Allow
              Resource: !Sub 'arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stack/*/*'
            - Sid: CloudGuardOnboardingOrchestratorIamListAccount
              Action:
                - 'iam:ListAccountAliases'
              Effect: Allow
              Resource: '*'
            - Sid: CloudGuardOnboardingOrchestratorSelfDistruction
              Action:
                - 'lambda:DeleteFunction'
              Effect: Allow
              Resource: !Join ["-", [!Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:CloudGuardOnboardingOrchestrator', !If [DeleteEvent, Delete, ''], !Select [3, !Split ['-', !Ref CloudGuardApiKeyId]]]]
            - Sid: CloudGuardOnboardingOrchestratorSelfDistructionDeleteSubscription
              Action:
                - 'SNS:Unsubscribe'
              Effect: Allow
              Resource: !Ref CloudGuardOnboardingSns
            - Sid: GetTemplate
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::cloudguard-unified-onboarding-${AWS::Region}REPLACEMENT_BUCKET_SUFFIX/*'
            - Sid: CloudGuardOnboardingOrchestratorIamPolicy
              Action:
                - 'iam:GetPolicy'
                - 'iam:CreatePolicy'
                - 'iam:DeletePolicy'
                - 'iam:ListPolicyVersions'
                - 'iam:CreatePolicyVersion'
                - 'iam:DeletePolicyVersion'
              Effect: Allow
              Resource:
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CloudGuard-Connect-RO-policy${UniqueSuffix}'
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CloudGuard-Connect-RW-policy${UniqueSuffix}'
            - REPLACEMENT_ORCHESTRATOR_ROLE_POLICY_STATEMENTS

    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Tags:
      - Key: ConditionalDependsOn
        Value: !If [ RemoteStackModifyEnabled, !Ref CloudGuardOnboardingStackModifyPermissions, Ignored ]
