OnboardingId:
  Description: The id of the onboarding process
  Type: String
ApiBaseUrl:
  Description: The base url of the CloudGuard web API
  Type: String
CloudGuardApiKeyId:
  Description: The CloudGuard service account API Key Id
  Type: String
CloudGuardApiKeySecret:
  Description: The CloudGuard service account API Key secret
  Type: String
Version:
  Description: The CloudGuard onboarding version
  Type: String
EnableRemoteStackModify:
  Description: Whether CloudGuard have permissions to update or delete the stack
  Type: String
  Default: true
  AllowedValues:
    - true
    - false
UniqueSuffix:
  Description: An optional suffix for all resources
  Type: String
  Default: ''
  MaxLength: 19
DeleteInnerResources:
  Description: Whether to delete Lambda inner resources
  Type: String
  Default: false
  AllowedValues:
    - true
    - false
UseAwsReadOnlyPolicy:
  Description: When enabled, CloudGuard uses the AWS ReadOnlyAccess policy that grants CloudGuard permissions to support new services in the future
  Type: String
  AllowedValues:
    - Enable
    - Disable
  Default: Enable